services:
  postgres-db:
    profiles: ["linux"]
    image: postgres:15.4-alpine3.18
    ports:
      - "5432:5432"
    volumes:
      - ./data/.postgres:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: pass

  postgres-db-mac:
    profiles: ["macos"]
    image: postgres:15.4
    ports:
      - "5432:5432"
    volumes:
      - ./data/.postgres:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: pass

  cassandra_db:
    image: cassandra:4.1.3
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./data/.cassandra:/var/lib/cassandra
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
      - CASSANDRA_CLUSTER_NAME=cassandra-akka-cluster
    networks:
        - cassandra_network

  cassandra_temp:
    image: cassandra:4.1.3
    volumes:
      - ./cassandra/scripts/bash:/docker-entrypoint.sh
      - ./cassandra/scripts/cql:/tmp/cql
    networks:
      - cassandra_network
    command: >
      bash ./docker-entrypoint.sh/execute-cql.sh

  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./data/.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  cassandra_network: